export enum CurrentEvents {
  SET_USER = 'SET_USER',
  SET_PROFILE = 'SET_PROFILE',
  SET_FIREBASE = 'SET_FIREBASE',
  SET_CONFIG = 'SET_CONFIG',
  SET_SPONSORS = 'SET_SPONSORS',

  LOAD_SITE_DATA = 'LOAD_SITE_DATA',
}

export enum ConfigEvents {
  SET_CONFIG_OPEN = 'SET_CONFIG_OPEN',
  SET_CONFIG_CLOSE = 'SET_CONFIG_CLOSE'
}

export enum AdminEvents {
  TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE',
  TOGGLE_CREATE_MENU = 'TOGGLE_CREATE_MENU',
  SET_SPEAKER_EDITOR_OPEN = 'SET_SPEAKER_EDITOR_OPEN',
  SET_SESSION_EDITOR_OPEN = 'SET_SESSION_EDITOR_OPEN'
}

export enum DialogEvents {
  OPEN_DIALOG = 'OPEN_DIALOG',
  CLOSE_DIALOG = 'CLOSE_DIALOG'
}

export enum SpeakerEvents {
  SET_SPEAKERS = 'SET_SPEAKERS',
  SET_EDITOR_STATE = 'SET_EDITOR_STATE',
  CLEAR_EDITOR_STATE = 'CLEAR_EDITOR_STATE'
}

export enum SessionEvents {
  SET_SESSION = 'SET_SESSION',
  SET_SESSION_STATE = 'SET_SESSION_STATE',
  CLEAR_SESSION_STATE = 'CLEAR_SESSION_STATE'
}

export enum EditorEvents {
  EDIT_SPEAKER = 'EDIT_SPEAKER',
  EDIT_SESSION = 'EDIT_SESSION'
}